/**
 * MAD-AAG WEBSITE — MAIN ENGINE (app.js)
 * Do not edit this file. Edit data/site.js and data/meetings.js instead.
 */

/* ── ROUTER ─────────────────────────────────────────────── */
let currentMeetingYear = null;

function showPage(id, opts) {
  opts = opts || {};
  document.querySelectorAll('.page').forEach(function(p) { p.classList.remove('active'); });
  document.querySelectorAll('.nav-link').forEach(function(a) { a.classList.remove('active'); });
  document.querySelector('nav').classList.remove('open');
  // Close meetings dropdown
  var dd = document.getElementById('meetings-nav-dropdown');
  if (dd) dd.classList.remove('open');

  var page = document.getElementById('page-' + id);
  if (page) {
    page.classList.add('active');
    document.querySelectorAll('.nav-link[data-page="' + id + '"]').forEach(function(a) { a.classList.add('active'); });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  if (id === 'meeting-detail' && opts.year) {
    currentMeetingYear = opts.year;
    renderMeetingDetail(opts.year);
    location.hash = 'meeting-' + opts.year;
  } else {
    location.hash = id;
  }
}

/* ── MEETINGS DROPDOWN TOGGLE ───────────────────────────── */
function toggleMeetingsDropdown(e) {
  e.preventDefault();
  e.stopPropagation();
  var dd = document.getElementById('meetings-nav-dropdown');
  dd.classList.toggle('open');
}

document.addEventListener('click', function(e) {
  var dd = document.getElementById('meetings-nav-dropdown');
  if (dd && !dd.contains(e.target)) {
    dd.classList.remove('open');
  }
});

/* ── HELPER: sorted meetings ────────────────────────────── */
function sortedMeetings() {
  return (window.MEETINGS || []).slice().sort(function(a, b) { return b.year - a.year; });
}

/* ── HELPER: officer photo ──────────────────────────────── */
function officerPhotoHTML(officer) {
  var fname = officer.photo;
  var path  = fname && window.PHOTOS && window.PHOTOS.officers && window.PHOTOS.officers[fname];
  var initials = officer.name.split(' ').map(function(w) { return w[0]; }).join('').slice(0,2).toUpperCase();
  if (path) {
    return '<div class="officer-photo-wrap"><img src="' + path + '" alt="' + officer.name + '" loading="lazy" onerror="this.parentElement.innerHTML=\'<div class=&quot;officer-avatar&quot;>' + initials + '</div>\'"></div>';
  }
  return '<div class="officer-photo-wrap"><div class="officer-avatar">' + initials + '</div></div>';
}

/* ── HELPER: photo grid ─────────────────────────────────── */
function photoGridHTML(photos, year) {
  return (photos || []).map(function(p) {
    var src = (year && window.PHOTOS && window.PHOTOS.meetings && window.PHOTOS.meetings[year] && window.PHOTOS.meetings[year][p.src]) || p.src;
    var hasReal = src && !p.placeholder;
    if (hasReal) {
      return '<div class="photo-slot' + (p.tall ? ' tall' : '') + '"><img src="' + src + '" alt="' + p.caption + '" loading="lazy"></div>';
    }
    return '<div class="photo-slot' + (p.tall ? ' tall' : '') + '"><div class="photo-placeholder"><div class="ico">📷</div><p>' + p.caption + '</p></div></div>';
  }).join('');
}

/* ── RENDER: HOME ───────────────────────────────────────── */
function renderHome() {
  var S = window.SITE;
  var meetings = sortedMeetings();
  var next = meetings[0] || {};

  document.getElementById('home-facts').innerHTML = (S.facts || []).map(function(f) {
    return '<div class="fact"><div class="fact-number">' + f.number + '</div><div class="fact-label">' + f.label + '</div></div>';
  }).join('');

  document.getElementById('home-about').textContent = S.about || '';

  var news = (S.announcements || []).slice(0, 3);
  document.getElementById('home-news').innerHTML = news.map(function(n, i) {
    var tagClass = (n.type === 'info' || n.type === 'meeting') ? 'meeting' : 'announce';
    var tagLabel = n.type === 'info' ? 'Update' : (n.type === 'meeting' ? 'Meeting' : 'Announcement');
    var preview  = n.body.length > 120 ? n.body.slice(0, 120) + '…' : n.body;
    return '<div class="card home-news-card" style="margin-bottom:14px;cursor:pointer;" onclick="goToAnnouncement(' + i + ')" role="button" tabindex="0" onkeydown="if(event.key===\'Enter\'||event.key===\' \'){goToAnnouncement(' + i + ')}">'
      + '<div class="card-date">' + n.date + '</div>'
      + '<span class="tag tag-' + tagClass + '">' + tagLabel + '</span>'
      + '<h3 style="color:var(--navy);font-size:1rem;margin-bottom:6px;">' + n.title + '</h3>'
      + '<p style="font-size:.88rem;color:var(--muted);margin:0 0 10px;">' + preview + '</p>'
      + '<span style="font-size:.8rem;font-family:var(--ff-label);font-weight:700;color:var(--teal);">Read more →</span>'
      + '</div>';
  }).join('');

  document.getElementById('home-next-meeting').innerHTML = '<div class="card" style="max-width:700px;padding:32px;">'
    + '<p class="eyebrow" style="margin-bottom:4px;">' + (next.status === 'upcoming' ? 'Upcoming' : 'Most Recent') + '</p>'
    + '<h2 style="margin-bottom:6px;color:var(--navy);">' + (next.title || '') + '</h2>'
    + (next.theme ? '<p style="font-style:italic;color:var(--teal);font-family:var(--ff-display);margin-bottom:14px;">"' + next.theme + '"</p>' : '')
    + '<div style="display:flex;gap:22px;flex-wrap:wrap;margin-bottom:20px;font-size:.9rem;">'
    + '<span>📅 ' + (next.date || '') + '</span>'
    + '<span>📍 ' + (next.location || '') + '</span>'
    + '</div>'
    + '<a class="btn btn-primary" onclick="showPage(\'meetings\');return false;">View Meeting Details →</a>'
    + '</div>';
}

/* ── RENDER: OFFICERS ───────────────────────────────────── */
function officerCardHTML(o) {
  return '<div class="officer-card">'
    + officerPhotoHTML(o)
    + '<div class="officer-top-bar"></div>'
    + '<div class="officer-body">'
    + '<div class="officer-role">' + o.role + '</div>'
    + '<div class="officer-name">' + o.name + '</div>'
    + '<div class="officer-inst">' + o.institution + '<br>' + o.location + '</div>'
    + (o.bio ? '<p class="officer-bio">' + o.bio + '</p>' : '')
    + (o.email ? '<div class="officer-email"><a href="mailto:' + o.email + '">' + o.email + '</a></div>' : '')
    + '</div></div>';
}

function renderOfficers() {
  var S = window.SITE;
  document.getElementById('officers-grid').innerHTML = (S.officers || []).map(officerCardHTML).join('');

  var past = S.pastOfficers || [];
  var pastSection = document.getElementById('past-officers-section');
  if (!past.length) { if (pastSection) pastSection.style.display = 'none'; return; }

  document.getElementById('past-term-tabs').innerHTML = past.map(function(t, i) {
    return '<button class="term-tab' + (i === 0 ? ' active' : '') + '" onclick="selectTerm(' + i + ')" id="term-tab-' + i + '">' + t.term + '</button>';
  }).join('');

  document.getElementById('past-term-panels').innerHTML = past.map(function(t, i) {
    return '<div class="term-panel' + (i === 0 ? ' active' : '') + '" id="term-panel-' + i + '"><div class="grid-3">' + t.officers.map(officerCardHTML).join('') + '</div></div>';
  }).join('');
}

function selectTerm(i) {
  document.querySelectorAll('.term-tab').forEach(function(el, j) { el.classList.toggle('active', i === j); });
  document.querySelectorAll('.term-panel').forEach(function(el, j) { el.classList.toggle('active', i === j); });
}

function togglePastOfficers() {
  var body    = document.getElementById('past-officers-body');
  var chevron = document.getElementById('past-officers-chevron');
  var btn     = document.getElementById('past-officers-toggle');
  var isOpen  = !body.hidden;
  body.hidden = isOpen;
  chevron.classList.toggle('rotated', !isOpen);
  btn.setAttribute('aria-expanded', String(!isOpen));
}

/* ── RENDER: MEMBERSHIP ─────────────────────────────────── */
function renderMembership() {
  var S = window.SITE;
  document.getElementById('membership-intro').textContent = S.membershipIntro || '';
  document.getElementById('membership-benefits').innerHTML = (S.membershipBenefits || []).map(function(b) {
    return '<div class="benefit-item"><div class="benefit-icon">' + b.icon + '</div><div class="benefit-text"><h4>' + b.title + '</h4><p>' + b.text + '</p></div></div>';
  }).join('');
}

/* ── RENDER: MEETINGS ───────────────────────────────────── */
function renderMeetings() {
  var meetings = sortedMeetings();
  var next = meetings.find(function(m) { return m.status === 'upcoming'; }) || meetings[0];
  var past = meetings.filter(function(m) { return m.status === 'past'; });

  if (!next) return;

  document.getElementById('mtg-hero-title').textContent = next.title;
  document.getElementById('mtg-hero-theme').textContent = next.theme ? '"' + next.theme + '"' : '';
  document.getElementById('mtg-hero-meta').innerHTML =
    '<div class="meta-chip"><span class="ico">📅</span>' + next.date + '</div>'
    + '<div class="meta-chip"><span class="ico">📍</span>' + next.location + '</div>'
    + (next.host ? '<div class="meta-chip"><span class="ico">🏛️</span>' + next.host + '</div>' : '');

  var actions = [
    next.cfpLink     ? '<a class="btn btn-primary" href="' + next.cfpLink     + '" target="_blank">Submit Abstract</a>' : '',
    next.regLink     ? '<a class="btn btn-outline" href="' + next.regLink     + '" target="_blank">Register</a>'        : '',
    next.programLink ? '<a class="btn btn-outline" href="' + next.programLink + '" target="_blank">View Program</a>'    : ''
  ].filter(Boolean).join('');
  document.getElementById('mtg-hero-actions').innerHTML = actions || '<span style="color:rgba(255,255,255,.6);font-size:.9rem;">Registration details coming soon</span>';

  document.getElementById('mtg-description').innerHTML = '<p style="color:var(--muted);">' + (next.description || '') + '</p>'
    + (next.keynote ? '<p style="color:var(--muted);"><strong>Keynote:</strong> ' + next.keynote + '</p>' : '');

  document.getElementById('mtg-schedule').innerHTML = (next.schedule || []).length
    ? '<table class="schedule-table">' + next.schedule.map(function(s) { return '<tr><td class="schedule-time">' + s.time + '</td><td>' + s.event + '</td></tr>'; }).join('') + '</table>'
    : '<p style="color:var(--muted);font-size:.9rem;">Schedule will be posted closer to the meeting date.</p>';

  document.getElementById('mtg-photos').innerHTML = photoGridHTML(next.photos || [], next.year);

  document.getElementById('mtg-past-list').innerHTML = past.map(function(m) {
    return '<div class="past-meeting-row">'
      + '<div class="past-year">' + m.year + '</div>'
      + '<div class="past-info"><div class="past-title">' + m.title + '</div>'
      + (m.location ? '<div class="past-loc">📍 ' + m.location + '</div>' : '')
      + '</div>'
      + '<a class="past-link" onclick="showPage(\'meeting-detail\',{year:' + m.year + '});return false;">View Archive →</a>'
      + '</div>';
  }).join('');
}

/* ── RENDER: MEETING DETAIL ─────────────────────────────── */
function renderMeetingDetail(year) {
  var m = (window.MEETINGS || []).find(function(x) { return x.year == year; });
  if (!m) return;

  document.getElementById('archive-year').textContent  = m.year;
  document.getElementById('archive-title').textContent = m.title;
  document.getElementById('archive-theme').textContent = m.theme ? '"' + m.theme + '"' : '';
  document.getElementById('archive-meta').innerHTML =
    '<div class="meta-chip"><span class="ico">📅</span>' + m.date + '</div>'
    + (m.location ? '<div class="meta-chip"><span class="ico">📍</span>' + m.location + '</div>' : '')
    + (m.host     ? '<div class="meta-chip"><span class="ico">🏛️</span>' + m.host + '</div>'     : '')
    + (m.keynote  ? '<div class="meta-chip"><span class="ico">🎤</span>Keynote: ' + m.keynote + '</div>' : '');

  document.getElementById('archive-links').innerHTML = [
    m.programLink ? '<a class="btn btn-primary btn-sm" href="' + m.programLink + '" target="_blank">View Program</a>' : '',
    m.cfpLink     ? '<a class="btn btn-ghost btn-sm"   href="' + m.cfpLink     + '" target="_blank">Original CFP</a>' : ''
  ].filter(Boolean).join('');

  document.getElementById('archive-description').innerHTML = '<p style="color:var(--muted);">' + (m.description || '') + '</p>';

  document.getElementById('archive-highlights').innerHTML = (m.highlights || []).length
    ? '<ul class="highlights-list">' + m.highlights.map(function(h) { return '<li>' + h + '</li>'; }).join('') + '</ul>'
    : '<p style="color:var(--muted);font-size:.9rem;">No highlights recorded.</p>';

  document.getElementById('archive-awards').innerHTML = (m.awards || []).length
    ? '<table class="awards-table"><thead><tr><th>Award</th><th>Recipient</th><th>Institution</th></tr></thead><tbody>'
      + m.awards.map(function(a) { return '<tr><td class="award-name">' + a.award + '</td><td>' + a.recipient + '</td><td>' + a.institution + '</td></tr>'; }).join('')
      + '</tbody></table>'
    : '<p style="color:var(--muted);font-size:.9rem;">Award records not yet entered.</p>';

  document.getElementById('archive-schedule').innerHTML = (m.schedule || []).length
    ? '<table class="schedule-table">' + m.schedule.map(function(s) { return '<tr><td class="schedule-time">' + s.time + '</td><td>' + s.event + '</td></tr>'; }).join('') + '</table>'
    : '<p style="color:var(--muted);font-size:.9rem;">Schedule not recorded.</p>';

  document.getElementById('archive-photos').innerHTML = (m.photos || []).length
    ? photoGridHTML(m.photos, m.year)
    : '<p style="color:var(--muted);">No photos available for this meeting.</p>';
}

/* ── RENDER: ANNOUNCEMENTS ──────────────────────────────── */
function buildAnnounceHTML(items, idPrefix) {
  var PREVIEW = 130;
  return (items || []).map(function(a, i) {
    var isLong  = a.body.length > PREVIEW;
    var preview = isLong ? a.body.slice(0, PREVIEW).trimEnd() + '…' : a.body;
    var labels  = { info: 'Update', urgent: 'Important', meeting: 'Meeting', '': 'Announcement' };
    var typeLabel = labels[a.type || ''] || 'Announcement';
    var tagType   = (a.type === 'meeting' || a.type === 'info') ? 'meeting' : (a.type || 'default');
    var uid = idPrefix + '-' + i;

    return '<div class="announce-item ' + (a.type || '') + '" id="announce-' + uid + '">'
      + '<div class="announce-header" onclick="toggleAnnounceById(\'' + uid + '\')" role="button" aria-expanded="false" tabindex="0">'
      + '<div class="announce-header-left">'
      + '<span class="announce-tag announce-tag-' + tagType + '">' + typeLabel + '</span>'
      + '<div class="meta">Posted ' + a.date + '</div>'
      + '<h3>' + a.title + '</h3>'
      + '<p class="announce-preview" id="announce-preview-' + uid + '">' + preview.replace(/\n/g, '<br>') + '</p>'
      + '</div>'
      + (isLong ? '<div class="announce-chevron" id="announce-chevron-' + uid + '" aria-hidden="true"><svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M4.5 6.75L9 11.25L13.5 6.75" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></div>' : '')
      + '</div>'
      + (isLong ? '<div class="announce-body" id="announce-body-' + uid + '" hidden><p>' + a.body.replace(/\n/g, '<br>') + '</p>'
        + (a.link ? '<a class="btn btn-teal btn-sm" href="' + a.link + '" target="_blank" style="margin-top:8px;">' + (a.linkLabel || 'Learn More') + ' →</a>' : '')
        + '</div>' : '')
      + '</div>';
  }).join('');
}

function toggleAnnounceById(uid) {
  var body    = document.getElementById('announce-body-' + uid);
  var preview = document.getElementById('announce-preview-' + uid);
  var chevron = document.getElementById('announce-chevron-' + uid);
  var header  = document.querySelector('#announce-' + uid + ' .announce-header');
  if (!body) return;
  var isOpen = !body.hidden;
  body.hidden    = isOpen;
  preview.hidden = !isOpen;
  if (chevron) chevron.classList.toggle('rotated', !isOpen);
  header.setAttribute('aria-expanded', String(!isOpen));
}

function renderAnnouncements() {
  document.getElementById('announcements-list').innerHTML = buildAnnounceHTML(window.SITE.announcements || [], 'cur');
  var archiveEl = document.getElementById('announcements-archive-list');
  if (archiveEl) archiveEl.innerHTML = buildAnnounceHTML(window.SITE.archivedAnnouncements || [], 'arc');
}

function toggleArchive() {
  var body    = document.getElementById('archive-body');
  var chevron = document.getElementById('archive-chevron');
  var btn     = document.getElementById('archive-toggle');
  var isOpen  = !body.hidden;
  body.hidden = isOpen;
  chevron.classList.toggle('rotated', !isOpen);
  btn.setAttribute('aria-expanded', String(!isOpen));
}

function goToAnnouncement(index) {
  showPage('announcements');
  setTimeout(function() {
    var uid  = 'cur-' + index;
    var body = document.getElementById('announce-body-' + uid);
    if (body && body.hidden) toggleAnnounceById(uid);
    var card = document.getElementById('announce-' + uid);
    if (card) card.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }, 50);
}

/* ── BUILD MEETINGS DROPDOWN ────────────────────────────── */
function buildMeetingsDropdown() {
  var meetings = sortedMeetings();
  var upcoming = meetings.filter(function(m) { return m.status === 'upcoming'; });
  var past     = meetings.filter(function(m) { return m.status === 'past'; });

  var html = '';

  if (upcoming.length) {
    html += '<div class="dropdown-divider">Upcoming</div>';
    upcoming.forEach(function(m) {
      html += '<a onclick="showPage(\'meetings\');return false;"><span class="dropdown-year">' + m.year + '</span> ' + m.title + '</a>';
    });
  }

  if (past.length) {
    html += '<div class="dropdown-divider">Past Meetings</div>';
    past.forEach(function(m) {
      html += '<a onclick="showPage(\'meeting-detail\',{year:' + m.year + '});return false;"><span class="dropdown-year">' + m.year + '</span> ' + m.title + '</a>';
    });
  }

  document.getElementById('meetings-dropdown').innerHTML = html;
}

/* ── BUILD FOOTER ───────────────────────────────────────── */
function buildFooter() {
  var S = window.SITE;
  document.getElementById('footer-year').textContent      = new Date().getFullYear();
  document.getElementById('footer-region').innerHTML      = S.region;
  document.getElementById('footer-aag-url').href          = S.aagUrl;
  document.getElementById('footer-aag-url').textContent   = S.aagUrl.replace('https://', '');

  var meetings = sortedMeetings().filter(function(m) { return m.status === 'past'; }).slice(0, 4);
  document.getElementById('footer-meetings').innerHTML = meetings.map(function(m) {
    var short = m.title.length > 30 ? m.title.slice(0, 30) + '…' : m.title;
    return '<li><span onclick="showPage(\'meeting-detail\',{year:' + m.year + '})">' + m.year + ' — ' + short + '</span></li>';
  }).join('');
}

/* ── ROUTE FROM HASH ────────────────────────────────────── */
function routeFromHash() {
  var h = (location.hash || '#home').replace('#', '');
  if (h.startsWith('meeting-') && h.length > 8) {
    var yr = parseInt(h.replace('meeting-', ''), 10);
    if (!isNaN(yr)) { showPage('meeting-detail', { year: yr }); return; }
  }
  var valid = ['home','officers','membership','meetings','meeting-detail','announcements','newsletter'];
  showPage(valid.indexOf(h) !== -1 ? h : 'home');
}

/* ── INIT ───────────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', function() {
  renderHome();
  renderOfficers();
  renderMembership();
  renderMeetings();
  renderAnnouncements();
  buildMeetingsDropdown();
  buildFooter();
  window.addEventListener('hashchange', routeFromHash);
  routeFromHash();
});
